accumulate_grad_batches: 1
amp: false
base_config:
- ../sr_base.yaml
- ../df2k4x.yaml
batch_size: 32
binary_data_dir: BreizhSR
check_val_every_n_epoch: 10
clip_grad_norm: 0
crop_size: 320
data_augmentation: false
data_interp: bicubic
debug: false
ds_workers: 1
endless: false
eval_batch_size: 32
gen_dir_name: ''
hidden_size: 32
infer: false
load_ckpt: ''
loss_type: l1
lr: 0.0002
max_epochs: 2
max_updates: 400000
misr: false
num_block: 15
num_ckpt_keep: 100
num_sanity_val_steps: 4
num_workers: 8
patch_size: 160
print_nan_grads: false
resume_from_checkpoint: 0
save_best: true
save_ckpt_interval: 20000
save_codes:
- configs
- models
- tasks
- utils
save_intermediate: false
seed: 1234
sen2_amount: 1
sr_scale: 4
tb_log_interval: 100
test_batch_size: 1
test_crop_size:
- 2040
- 2040
test_diff: false
test_input_dir: ''
test_save_png: true
test_thresh_size: 0
thresh_size: 160
train_diffsr: false
trainer_cls: tasks.rrdb.RRDBSatTask
val_check_interval: 25000
valid_monitor_key: val_loss
valid_monitor_mode: min
valid_steps: 3
work_dir: checkpoints/sisr/rrdb_ckpt
